<?php
require '/app/vendor/autoload.php';require '/app/vendor/yiisoft/yii2/Yii.php';require '/tmp/progress-applier.php';require '/tmp/progress-handler.php';
new yii\console\Application(['id'=>'progress-test','basePath'=>'/tmp','vendorPath'=>'/app/vendor','extensions'=>[], 'components'=>['db'=>['class'=>yii\db\Connection::class,'dsn'=>'sqlite::memory:']]]);
$db=Yii::$app->db;$db->createCommand('CREATE TABLE test_state(connection_id TEXT,product_id INT,revision INT,applied_revision INT,needs_resolution INT,operation TEXT)')->execute();for($i=1;$i<=9;$i++)$db->createCommand()->insert('test_state',['connection_id'=>'test','product_id'=>$i,'revision'=>1,'applied_revision'=>0,'needs_resolution'=>0,'operation'=>'upsert'])->execute();
$c=new ReflectionClass(skeeks\cms\shop\gpd\CatalogApplier::class);$a=$c->newInstanceWithoutConstructor();foreach(['db'=>$db,'stateTable'=>'test_state','id'=>'test'] as $k=>$v){$p=$c->getProperty($k);$p->setAccessible(true);$p->setValue($a,$v);}
if($a->remaining()!==9||$a->remaining(9)!==0||$a->remaining(5)!==4)throw new RuntimeException('Pending rows counted twice');
class Reporter implements skeeks\cms\job\contracts\JobReporterInterface {
 public $total;public $warnings=0;public $result;
 public function setStage(string $s,?string $m=null):void{} public function setTotal(?int $n):void{$this->total=$n;} public function advance(int $n=1):void{} public function countSuccess(int $n=1):void{} public function countWarning(int $n=1):void{$this->warnings+=$n;} public function countError(int $n=1):void{} public function countSkipped(int $n=1):void{}
 public function info(string $m,array $c=[]):void{} public function warning(string $m,array $c=[]):void{} public function error(string $m,array $c=[]):void{} public function itemError(string $t,$id,string $m,array $r=[]):void{} public function heartbeat():void{} public function isCancelled():bool{return false;} public function addArtifact(string $t,string $p,array $o=[]):skeeks\cms\job\models\CmsJobRunArtifact{throw new LogicException();}public function setResult(array $r):void{$this->result=$r;}
}
$h=new skeeks\cms\shop\jobs\GpdCatalogApplyJobHandler();$r=new ReflectionClass($h);foreach(['service'=>$a,'settings'=>(object)['enabled'=>true]] as $k=>$v){$p=$r->getProperty($k);$p->setAccessible(true);$p->setValue($h,$v);}
$counts=array_fill_keys(['created','updated','deactivated','deleted','protected','pending','errors'],0);$counts['pending']=9;$ctx=new skeeks\cms\job\runtime\JobContext(['run'=>(object)['progress_current'=>9,'result_json'=>json_encode(['counts'=>$counts,'pending_details'=>[['product_id'=>1,'reason'=>'Missing enum']]])]]);$reporter=new Reporter();$m=$r->getMethod('finish');$m->setAccessible(true);$m->invoke($h,$ctx,$reporter);if($reporter->total!==9||$reporter->warnings!==9||$reporter->result['remaining']!==9||!$reporter->result['pending_details'])throw new RuntimeException('Finish reporting failed');echo "PASS: pending pagination, terminal 9/9, warnings and reasons\n";